apiVerspd: apps/v1
kind: Deployment
metadata:
  name: pd-deployment
  labels:
    app: pd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pd
  template:
    metadata:
      labels:
        app: pd
    spec:
      containers:
      - name: pd
        image: ssadcloud/rpd:v1.0
        ports:
        - containerPort: 80
